/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_download_format: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: any) => any;
export const wasm_extract_info: (a: number, b: number, c: number, d: number) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const wasm_bindgen__convert__closures_____invoke__h846ef15552bbf62d: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h97257f522bc2a4af: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hbb7b39079303fee0: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h36c0d255cecaed1b: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h6fbb77f9914c04a4: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
